name: CD - Prod Server

on:
  workflow_dispatch: # 수동 실행만 가능

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "배포 시작"
            cd /root/dodream-prod

            echo "최신 코드 가져오기"
            git pull origin main

            echo "의존성 설치"
            npm ci

            echo "프로젝트 빌드"
            npm run build

            echo "서버 재시작"
            pm2 restart prod --update-env
            pm2 save

            echo "✅ 프로덕션 서버 배포 완료"
            pm2 info prod
